### PR TITLE
Feature - Paulus 2 exception compatibility

### PR DESCRIPTION
**Pull request by Rican7**
This PR improves the Paulus exception handling and is a necessity for the exception changes in Rican7/Paulus#5

Other than the obvious constant additions for compatibility, this PR also changes how the base `Api` controller class handles exceptions in the `handleException()` method. Previously this method was passing the exception to the parent handler, but was never halting afterwards. This caused a condition that allowed the exception to be handled multiple times (once in the `if` block and once in the last default expression). This was causing a number of problems, including throwing eventual fatal errors and Paulus attempting to send a response more than once (oops!).

### CODE REVIEW

**Comment by jstruzik** [comment]
Everything looks good here :+1:

**Comment by brianmuse** [comment]
All dat new stez. Looks great! I think you need to update the required version of paulus though in composer.json, right?

**Comment by Rican7** [comment]
Thanks!

@brianmuse The other PR is going into that release branch, which is what the composer.json points to, so no

**Comment by brianmuse** [comment]
Ah, I see that here: https://github.com/Rican7/PHP-Paulus-Components/blob/76d52047b5238e064b6ce9110b2e3cfcd0524da0/composer.json#L23

So this will have to be updated with that release branch is merged in, then.

**Comment by Rican7** [comment]
This PR depends on code from the Paulus PR, but no nothing will have to be updated on this project post-merge. This is a library, it doesn't have a lock file.

What _will_ have to be updated is the lock files for any projects (you know which) using this library and the Paulus FW. That's all.

**Comment by brianmuse** [comment]
LGTM :+1:

**Pull request merged**
