### PR TITLE
Feature - Paulus 2 exception handler

### PR DESCRIPTION
**Pull request by Rican7**
This PR is a follow up to the changes introduced in Rican7/Paulus#6.

This PR simply updates our `ApiApp` constructor to properly set the exception handler response and creates a new exception class for a "nicer" message during internal server errors.

### CODE REVIEW

**Comment by brianmuse** [comment]
Created that new class, but don't use it?

**Comment by Rican7** [comment]
We're using it somewhere else, but it was common enough to leave it here.
Most of the exceptions in this library aren't used directly in this library.... if not all of them.

**Comment by jstruzik** [comment]
Yeah it wouldn't really make sense to use the class here. This is more of a library that also has many defined exceptions.

**Comment by jstruzik** [comment]
:+1: !

**Comment by brianmuse** [comment]
Ah ok...a little strange to me to put classes in the scope of a library that the library itself doesn't use. But the nature of this repo is sorta a generic "toolkit", so that makes sense here, perhaps. :+1:

**Pull request merged**
